### PR TITLE
Rebase on upstream/master

### PR DESCRIPTION
**Pull request by alxdm**
Rebase on upstream/master https://github.com/snowflakedb/snowflake-kafka-connector.
There are changes specific only to this PR.
- `SnowflakeSinkTask.tableName` method was moved to `Utils`.
- `setAppendTableHash` metod was added to `SnowflakeSinkService` interface.

### CODE REVIEW

**Comment by alxdm** [comment]
I run test locally.

**Comment by alexdemidov** [comment]
After approval we have to rebase this branch onto master.

**Comment by ivan-klass** [comment]
I'm Ok to merge this also (if preferred over merge)

**Comment by alxdm** [comment]
We will use  [merge](https://github.com/invitae/snowflake-kafka-connector/pull/4).

**Pull request closed without merging**
